baseurl = "http://www.sslife.tech/"
languageCode = "ja"
title = "SS Life Tech"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; sslife.tech Copyright"
theme = 'vienna'

[params]
    image = "/images/bg.webp"
    # ga_api_key = "Your Google Analytics tracking id"
    author = "しょうちゃん"
    avatar = "/images/shota.webp"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "恵比寿で働くサーバーサイドエンジニア。隙きあらばGolangやってます。趣味はコーヒー、紅茶、旅行。ITツールが大好き。"
    subtitle = "しょうちゃんとしおりんのブログ"
    themecolor = "#fff" # Defines the tab color in Chrome for Android.
