version: '2'

tasks:
  serve:
    desc: "Serve"
    cmds:
      - hugo server -D
  blog-new:
    desc: "Create new blog"
    cmds:
      - hugo new blog/`date +%s`.md
  minify:
    desc: "Minify html"
    cmds:
      - html-minifier --collapse-whitespace --file-ext html --input-dir public --output-dir public
